security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        main:
#            security: false
        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            jwt: ~

        main:
            lazy: true
            provider: app_user_provider
            json_login:
#                check_path: app_login
                check_path: app_login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            logout:
                path: app_logout
                invalidate_session: true


    role_hierarchy:
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
#        ROLE_USER : PUBLIC_ACCESS
#        ROLE_ADMIN: ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_EMPLOYEE: ROLE_USER
        ROLE_MANAGER : ROLE_EMPLOYEE
        ROLE_PRESTATAIRE: ROLE_MANAGER
        ROLE_ADMIN: ROLE_PRESTATAIRE


    access_control:

        # - { path: ^/profile, roles: ROLE_USER }
     - { path: ^/$, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI
     - { path: ^/docs, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI docs
     - { path: ^/login, roles: PUBLIC_ACCESS }
#     - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
     - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email


when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: md5
                encode_as_base64: false
                iterations: 0
